[versions]
asmVer = "3.2.0"
# https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk18on
# https://www.bouncycastle.org/releasenotes.html
bcVer = "1.76"
commonCompressVer = "1.24.0"
coroutineVer = "1.7.3"
gsonVer = "2.10.1"
javassistVer = "3.29.2-GA"
javaxJsonVer = "1.1.4"
# openjfx LTS version needs Subscription https://mvnrepository.com/artifact/org.openjfx/javafx-controls
# jfx 20.x+ requires jdk 17+
jfxVer = "21"
jnaVer = "5.13.0"
kotlinSerVer = "1.6.0"
kotlinVer = "1.9.10"
mockitoCoreVer = "5.5.0"
nashornVer = "15.4"
seleniumVer = "4.12.1"
sqliteVer = "3.43.0.0"
tornadofxVer = "1.7.20"
zstdVer = "1.5.5-5"
zxingVer = "3.5.2"
jsoupVer = "1.16.1"

# plugin
# https://detekt.dev/changelog/
detektVer = "1.23.1"
javafxVer = "0.1.0"
# https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md
spotlessVer = "6.21.0"


[libraries]
asm = { module = "org.objectweb.asm:com.springsource.org.objectweb.asm", version.ref = "asmVer" }
bouncycastle = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bcVer" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commonCompressVer" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detektVer" }
gson = { module = "com.google.code.gson:gson", version.ref = "gsonVer" }
javassist = { module = "org.javassist:javassist", version.ref = "javassistVer" }
javax-json = { module = "org.glassfish:javax.json", version.ref = "javaxJsonVer" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jnaVer" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinVer" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerVer" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlinVer" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutineVer" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutineVer" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockitoCoreVer" }
nashron = { module = "org.openjdk.nashorn:nashorn-core", version.ref = "nashornVer" }
selenium = { module = "org.seleniumhq.selenium:selenium-java", version.ref = "seleniumVer" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqliteVer" }
tornadofx = { module = "no.tornado:tornadofx", version.ref = "tornadofxVer" }
zstd = { module = "com.github.luben:zstd-jni", version.ref = "zstdVer" }
zxing = { module = "com.google.zxing:javase", version.ref = "zxingVer" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoupVer" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektVer" }
javafx = { id = "org.openjfx.javafxplugin", version.ref = "javafxVer" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotlessVer" }
